In [39]:
import numpy as np
from mlxtend.data import loadlocal_mnist
import platform
import random
X, Y = loadlocal_mnist(
            images_path='TestImageFiles/train-images-idx3-ubyte', 
            labels_path='TestImageFiles/train-labels-idx1-ubyte')
Y = Y.reshape(60000,1)
random.seed(0)
chosen = random.sample(range(60000), 2000)
trainX = X[chosen]
trainY = Y[chosen]
onehotY = np.zeros((2000, 10))
for l in range(len(trainY)):
    onehotY[l, trainY[l]] = 1

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[7]


In [ ]:
from FromScratch import *

def neuralnetwork(X, Y, dimensions, iterations = 3000, learning_rate = 0.05):
    params = initialize_params(dimensions)
    for i in range(iterations):
        AL, caches = model_forward(X, params)
        grads = model_backward(AL, Y, caches)
        params = update_parameters(params, grads, learning_rate)
    return params


In [ ]:
dimensions= [2000, 30,10,10]
neuralnetwork(trainX, onehotY, dimensions = dimensions, iterations = 3000, learning_rate = 0.05)